version: '3'

services:
  wekandb:
    image: mongo:4.0
    container_name: wekandb
    restart: always
    volumes:
      - ./db:/data/db

  wekan:
    image: wekanteam/wekan
    container_name: wekan
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://localhost:8080
      - PORT=8080
    depends_on:
      - wekandb
